"""
Claude Analyst Skill — The AI Brain Layer
Uses Anthropic Files API + Code Execution tool to analyze any business file.
Claude does ALL thinking: cleaning, analysis, chart generation, insight writing.
Returns complete instruction packages for Excel and PPT skills.

Exposes:
  analyze_and_plan(file_path, session_id) → dict
  ask_question(question, csv_path, session_id) → str
"""

import json
import logging
import os
import re
import traceback

import anthropic

logger = logging.getLogger(__name__)

API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
MODEL = "claude-sonnet-4-6"
BETA_FLAGS = ["files-api-2025-04-14"]
MAX_TOKENS = 16384

SYSTEM_PROMPT = """You are a senior business data analyst. You will receive a business data file. Your job is to:

1. Load and fully understand the file — detect encoding, separator, header rows, merged cells, data quality issues. Use pandas to read the file. If it's CSV, try different encodings and separators. If it's Excel, read all sheets and pick the one with the most data.

2. Clean it completely — fix headers, remove blank rows, handle merged cells, standardize formats, convert types. Drop columns that are entirely empty. Strip whitespace from string columns.

3. Understand what kind of business data this is and what analysis would be most valuable to a senior executive.

4. Generate 4-6 professional charts as PNG files using matplotlib. Choose chart types that best tell the story of this data. Use these style rules:
   - Figure size: (10, 5) for most charts, (10, 6) for complex ones
   - Color palette: use professional blues (#1F3864, #2E75B6, #4472C4, #5B9BD5, #9DC3E6) with accent orange (#ED7D31) for highlights
   - Font sizes: title=14 bold, axis labels=11, tick labels=10
   - Always remove top and right spines
   - Always add subtle grid (axis='y', alpha=0.3)
   - Format large numbers with commas
   - Use tight_layout()
   - DPI: 150
   Save each chart to chart_0.png, chart_1.png, etc. in the current working directory.

5. Write 4-6 plain English insights a CEO would care about. Each insight should be specific with actual numbers, not vague statements.

6. Identify 3-4 KPIs with their values. Format values nicely (e.g., "$1.2M" not "1234567.89").

7. Define 2-3 useful pivot table structures showing groupings that reveal patterns.

8. Save the cleaned data as cleaned_data.csv in the current working directory.

9. Design a full PowerPoint slide structure (5-8 slides). Include:
   - A title slide
   - A KPI overview slide
   - 2-4 chart slides (one chart per slide with a caption explaining the insight)
   - An insights/key findings slide
   - A closing slide

IMPORTANT: After doing all the analysis and saving all files, you MUST print a single JSON object as your final output. Print ONLY the JSON, wrapped in ```json``` code fences. The JSON must have this exact structure:

```json
{
  "analysis_summary": "2-3 sentence summary of what this data shows, written for a business audience",
  "dataset_title": "Professional title for the report (e.g., 'Automobile Sales Performance Q1 2025')",
  "dataset_type": "what kind of data this is (e.g., 'sales', 'financial', 'inventory', 'hr')",
  "charts_generated": 4,
  "chart_filenames": ["chart_0.png", "chart_1.png", "chart_2.png", "chart_3.png"],
  "kpis": [
    {"label": "Total Revenue", "value": "$1.2M", "icon": "💰"},
    {"label": "Growth Rate", "value": "+15.3%", "icon": "📈"}
  ],
  "insights": [
    "Revenue grew 15.3% year-over-year, driven primarily by the North region.",
    "Product category X accounts for 42% of total sales but only 28% of profit margin."
  ],
  "pivot_instructions": [
    {"title": "Revenue by Region", "index_col": "Region", "value_col": "Revenue", "agg": "sum"},
    {"title": "Average Order Value by Product", "index_col": "Product", "value_col": "Order_Value", "agg": "mean"}
  ],
  "ppt_theme": "blue_white",
  "ppt_slides": [
    {"type": "title", "heading": "Automobile Sales Performance Q1 2025"},
    {"type": "kpi", "heading": "Key Metrics Overview", "content": [{"label": "Total Revenue", "value": "$1.2M", "icon": "💰"}]},
    {"type": "chart", "heading": "Revenue Trend", "content": {"chart_index": 0, "caption": "Revenue has grown steadily over the past 12 months."}},
    {"type": "insights", "heading": "Key Findings", "content": ["Insight 1", "Insight 2"]},
    {"type": "closing", "heading": "Thank You", "content": {"message": "Generated by Office Bot AI Analyst"}}
  ]
}
```

Rules:
- Be intelligent. If there is no date column, do NOT try to make trend charts — make comparison and distribution charts instead.
- If the data is messy, clean it silently without complaining.
- Never say you can't do something — figure it out.
- chart_index in ppt_slides refers to the index in chart_filenames array.
- Use the right chart types: bar for comparison, line for trends, pie for composition, scatter for correlation, horizontal bar for rankings.
"""

QUESTION_PROMPT = """You are a senior business data analyst. You have already analyzed a business dataset.
The user is asking a question about their data. Answer it directly and specifically with actual numbers from the data.
Be concise — 2-4 sentences max. Use plain English a non-technical person would understand.
If you need to calculate something, use the code execution tool to run Python code on the CSV file."""


def _create_client() -> anthropic.Anthropic:
    """Create Anthropic client with API key validation."""
    if not API_KEY:
        raise ValueError("ANTHROPIC_API_KEY environment variable is not set")
    return anthropic.Anthropic(api_key=API_KEY)


def _extract_json_from_text(text: str) -> dict | None:
    """Extract JSON from Claude's text response (may be in code fences)."""
    # Try to find JSON in code fences first
    match = re.search(r"```(?:json)?\s*\n?(.*?)\n?\s*```", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    # Try to find raw JSON object
    match = re.search(r"\{[\s\S]*\}", text)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass

    return None


def _extract_file_ids(response) -> list[str]:
    """Extract all output file IDs from a Claude response with code execution."""
    file_ids = []
    for block in response.content:
        # Handle bash execution results
        if hasattr(block, "type") and block.type == "bash_code_execution_tool_result":
            content = block.content
            if hasattr(content, "type") and content.type == "bash_code_execution_result":
                if hasattr(content, "content") and content.content:
                    for item in content.content:
                        if hasattr(item, "file_id"):
                            file_ids.append(item.file_id)
    return file_ids


def _extract_text(response) -> str:
    """Extract all text blocks from Claude response."""
    texts = []
    for block in response.content:
        if hasattr(block, "type") and block.type == "text":
            texts.append(block.text)
    return "\n".join(texts)


def analyze_and_plan(file_path: str, session_id: str) -> dict:
    """
    Analyze a business file using Claude's code execution.

    Args:
        file_path: Path to the uploaded file (CSV, XLS, XLSX)
        session_id: Unique session identifier for organizing output files

    Returns:
        Complete instruction dict ready for excel_skill and ppt_skill.

    Raises:
        ValueError: If file cannot be processed
        Exception: On API errors
    """
    client = _create_client()

    # Create output directory
    output_dir = f"/tmp/analyst_output/{session_id}"
    os.makedirs(output_dir, exist_ok=True)

    # Step 1: Upload file to Files API
    logger.info("Uploading file to Anthropic Files API: %s", file_path)
    with open(file_path, "rb") as f:
        uploaded_file = client.beta.files.upload(file=f)
    file_id = uploaded_file.id
    logger.info("File uploaded: file_id=%s", file_id)

    # Step 2: Send to Claude with code execution
    logger.info("Sending to Claude for analysis with code execution...")

    user_message = {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": (
                    "Analyze this business data file completely. "
                    "Generate all charts, insights, KPIs, and the full slide structure. "
                    "Save cleaned data as cleaned_data.csv and charts as chart_N.png files. "
                    "Then print the JSON result."
                ),
            },
            {
                "type": "container_upload",
                "file_id": file_id,
            },
        ],
    }

    messages = [user_message]

    response = client.beta.messages.create(
        model=MODEL,
        betas=BETA_FLAGS,
        max_tokens=MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=messages,
        tools=[{"type": "code_execution_20250825", "name": "code_execution"}],
    )

    # Accumulate file IDs and text from ALL turns (including paused ones)
    all_file_ids = _extract_file_ids(response)
    all_texts = [_extract_text(response)]

    # Handle pause_turn — keep looping until end_turn
    turn_count = 1
    while response.stop_reason == "pause_turn":
        turn_count += 1
        logger.info("Claude paused (turn %d), continuing...", turn_count)

        # Build continued conversation: original + assistant partial + continue prompt
        messages = [
            user_message,
            {"role": "assistant", "content": response.content},
            {"role": "user", "content": "Continue your analysis and print the final JSON."},
        ]

        response = client.beta.messages.create(
            model=MODEL,
            betas=BETA_FLAGS,
            max_tokens=MAX_TOKENS,
            system=SYSTEM_PROMPT,
            messages=messages,
            tools=[{"type": "code_execution_20250825", "name": "code_execution"}],
        )

        # Accumulate from this turn
        all_file_ids.extend(_extract_file_ids(response))
        all_texts.append(_extract_text(response))

    logger.info("Claude finished after %d turn(s). Stop reason: %s", turn_count, response.stop_reason)

    # Step 3: Extract text and parse JSON — search all accumulated text
    full_text = "\n".join(t for t in all_texts if t)
    analysis = _extract_json_from_text(full_text)

    if not analysis:
        logger.error("Failed to parse JSON from Claude's response. Full text:\n%s", full_text[:2000])
        raise ValueError(
            "Claude could not analyze this file. "
            "The file may be corrupt or in an unsupported format."
        )

    # Step 4: Download output files (charts + cleaned CSV) from ALL turns
    # Deduplicate file IDs
    unique_file_ids = list(dict.fromkeys(all_file_ids))
    logger.info("Found %d output files to download", len(unique_file_ids))

    chart_paths = []
    csv_path = None

    for fid in unique_file_ids:
        try:
            metadata = client.beta.files.retrieve_metadata(fid)
            filename = metadata.filename
            local_path = os.path.join(output_dir, filename)

            file_content = client.beta.files.download(fid)
            file_content.write_to_file(local_path)
            logger.info("Downloaded: %s → %s", filename, local_path)

            if filename.endswith(".csv"):
                csv_path = local_path
            elif filename.endswith(".png"):
                chart_paths.append(local_path)
        except Exception:
            logger.warning("Failed to download file %s:\n%s", fid, traceback.format_exc())

    # Sort chart paths by filename for consistent ordering
    chart_paths.sort()

    # Step 5: Clean up uploaded file from API
    try:
        client.beta.files.delete(file_id)
    except Exception:
        pass  # Non-critical

    # Step 6: Build the complete instruction package
    result = {
        # For Telegram summary message
        "analysis_summary": analysis.get("analysis_summary", "Analysis complete."),
        # For Excel skill
        "file_path": csv_path or file_path,  # Fall back to original if CSV download failed
        "charts": chart_paths,
        "insights": analysis.get("insights", []),
        "kpis": analysis.get("kpis", []),
        "pivot_instructions": analysis.get("pivot_instructions", []),
        "dataset_title": analysis.get("dataset_title", "Business Analysis"),
        "dataset_type": analysis.get("dataset_type", "general"),
        # For PPT skill
        "title": analysis.get("dataset_title", "Business Analysis"),
        "subtitle": "AI-Generated Analysis Report",
        "slides": analysis.get("ppt_slides", []),
        "theme": analysis.get("ppt_theme", "blue_white"),
        "chart_paths": chart_paths,
        # Metadata
        "charts_generated": len(chart_paths),
        "output_dir": output_dir,
    }

    logger.info(
        "Analysis complete: %d charts, %d insights, %d KPIs",
        len(chart_paths),
        len(result["insights"]),
        len(result["kpis"]),
    )

    return result


def ask_question(question: str, csv_path: str, session_id: str) -> str:
    """
    Ask a follow-up question about previously analyzed data.

    Args:
        question: User's question in natural language
        csv_path: Path to the cleaned CSV from a previous analysis
        session_id: Session identifier

    Returns:
        Claude's answer as a plain text string
    """
    client = _create_client()

    # Upload the CSV for context
    with open(csv_path, "rb") as f:
        uploaded_file = client.beta.files.upload(file=f)

    try:
        response = client.beta.messages.create(
            model=MODEL,
            betas=BETA_FLAGS,
            max_tokens=4096,
            system=QUESTION_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": question},
                        {"type": "container_upload", "file_id": uploaded_file.id},
                    ],
                }
            ],
            tools=[{"type": "code_execution_20250825", "name": "code_execution"}],
        )

        # Handle pause_turn
        while response.stop_reason == "pause_turn":
            response = client.beta.messages.create(
                model=MODEL,
                betas=BETA_FLAGS,
                max_tokens=4096,
                system=QUESTION_PROMPT,
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": question},
                            {"type": "container_upload", "file_id": uploaded_file.id},
                        ],
                    },
                    {"role": "assistant", "content": response.content},
                    {"role": "user", "content": "Please provide your answer."},
                ],
                tools=[{"type": "code_execution_20250825", "name": "code_execution"}],
            )

        return _extract_text(response) or "I wasn't able to answer that question. Please try rephrasing it."

    finally:
        # Clean up uploaded file
        try:
            client.beta.files.delete(uploaded_file.id)
        except Exception:
            pass
